### PR TITLE
[libsocialcache] Require kcalcore in pkgconfig

### PR DESCRIPTION
**Pull request by chriadam**
Fixes build breakage in dependent packages

### CODE REVIEW

**Comment by thp** [comment]
LGTM

**Comment by pgerdt** [comment]
I got a local build working by replacing
> QMAKE_PKGCONFIG_REQUIRES = libkcalcoren-qt5 libmkcal-qt5

with 

> QMAKE_PKGCONFIG_REQUIRES = libkcalcoren-qt5 uuid

**Comment by pvuorela** [comment]
Looks like both mkcal and kcalcore use uuid but only mkcal links against it. Suppose no code using only kcalcore compiles directly without knowing to add such linkage. Nice :)

**Comment by pgerdt** [comment]
LGTM

**Comment by pvuorela** [comment]
Created following, which I'd hope clears things up.
https://github.com/mer-packages/kcalcore/pull/6

**Comment by pvuorela** [comment]
Actually, wonder if any of this is needed if kcalcore does the right thing.

**Comment by pvuorela** [comment]
Yea, with updated kcalcore, buteo-sync-plugin-social starts to compile without changes here.

**Comment by chriadam** [comment]
Well, we should be good citizens and add libkcalcore to the .pc Requires for this package.  I've updated this PR to do only that one, now, as per MER#886

**Comment by pgerdt** [comment]
Still LGTM :)

**Comment by pvuorela** [comment]
LGTM.

**Pull request merged**
